@endpoint = http://localhost:10023

### Missing 'url' query parameter (400)
GET {{endpoint}}/api/get

### With parameter and large payload (200)
GET {{endpoint}}/api/get?url=http://bing.com

### With parameter and large payload (200)
GET {{endpoint}}/api/get?url=https://github.com

### With parameter and large payload (200)
GET {{endpoint}}/api/get?url=https://azure.microsoft.com/en-us/services/devops/

### With parameter and small payload (500)
GET {{endpoint}}/api/get?url=http://echo.jannemattila.com
